loggers:
  root:
    level: INFO
    appender-ref:
      ref: ConsoleLogger
server:
  port: 8081
  servlet:
    context-path: /universidade
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bancoUniPAvao
    username: mikael
    password: a.123456
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect