loggers:
  root:
    level: INFO
    appender-ref:
      ref: ConsoleLogger
server:
  port: 8081
  servlet:
    context-path: /universidade
spring:
  kafka:
    consumer:
      enable-auto-commit: true
      allow-auto-create-topics: true
      bootstrap-servers: 192.168.100.22:9092
      group-id: group_id_uni_pavao
    producer:
      offset-storage:
          topic: topico_uni_pavao
      status-storage:
          topic: topico_uni_pavao
      acks: all
      client-id: uni_pavao_id
      bootstrap-servers: 192.168.100.22:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bancoUniPAvao
    username: mikael
    password: a.123456
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect